### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/tc39-logo#2]

**Comment by syg** [comment]
People had suggested CC0. Are there *any* cons to using CC0?

**Comment by mathiasbynens** [comment]
Can we please get this resolved one way or another soon? I'd like to use the logo in a presentation.

**Comment by syg** [comment]
Waiting to see if Ecma execom has any objections to CC BY.

@mathiasbynens Any reservations about CC BY?

**Comment by mathiasbynens** [comment]
I'd personally be fine with any license that allows people to use the logo in presentations, preferably without having to also include the license itself or having to link to the logo repo every time. As such, I'd prefer CC0 over CC BY.

**Comment by mathiasbynens** [comment]
Thank you!
